version: '3'

services:
  soonroom-base:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    volumes:
      - mono-node-modules:/app/node_modules
